trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: LaravelDeploy
  displayName: 'Deploy Laravel to kijkeerst.nl'
  steps:

  - task: UseNode@1
    inputs:
      version: '18.x'
    displayName: 'Use Node.js 18'

  - script: |
      php -v
      composer --version || curl -sS https://getcomposer.org/installer | php && sudo mv composer.phar /usr/local/bin/composer
      composer install --no-interaction --prefer-dist --optimize-autoloader
    displayName: 'Install PHP Dependencies with Composer'

  - script: |
      npm install
      npm run build
    displayName: 'Install and Build Frontend (NPM)'

  - script: |
      php artisan migrate --force
      php artisan storage:link
    displayName: 'Run Laravel Commands'

  - script: |
      echo "Creating rsync filter file..."
      echo "- /.phpunit.cache" > $(Build.ArtifactStagingDirectory)/rsync-filter.txt
      echo "- /node_modules" >> $(Build.ArtifactStagingDirectory)/rsync-filter.txt
      echo "- /public/build" >> $(Build.ArtifactStagingDirectory)/rsync-filter.txt
      echo "- /public/hot" >> $(Build.ArtifactStagingDirectory)/rsync-filter.txt
      echo "- /public/storage" >> $(Build.ArtifactStagingDirectory)/rsync-filter.txt
      echo "- /storage/*.key" >> $(Build.ArtifactStagingDirectory)/rsync-filter.txt
      echo "- /vendor" >> $(Build.ArtifactStagingDirectory)/rsync-filter.txt
      echo "- /.env" >> $(Build.ArtifactStagingDirectory)/rsync-filter.txt
      echo "- /.env.*" >> $(Build.ArtifactStagingDirectory)/rsync-filter.txt
      echo "- /.phpactor.json" >> $(Build.ArtifactStagingDirectory)/rsync-filter.txt
      echo "- /.phpunit.result.cache" >> $(Build.ArtifactStagingDirectory)/rsync-filter.txt
      echo "- /Homestead.*" >> $(Build.ArtifactStagingDirectory)/rsync-filter.txt
      echo "- /auth.json" >> $(Build.ArtifactStagingDirectory)/rsync-filter.txt
      echo "- /npm-debug.log" >> $(Build.ArtifactStagingDirectory)/rsync-filter.txt
      echo "- /yarn-error.log" >> $(Build.ArtifactStagingDirectory)/rsync-filter.txt
      echo "- /.fleet" >> $(Build.ArtifactStagingDirectory)/rsync-filter.txt
      echo "- /.idea" >> $(Build.ArtifactStagingDirectory)/rsync-filter.txt
      echo "- /.vscode" >> $(Build.ArtifactStagingDirectory)/rsync-filter.txt
    displayName: 'Create rsync Filter File'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo "Deploying using rsync..."
        rsync -az --filter="merge $(Build.ArtifactStagingDirectory)/rsync-filter.txt" -e "ssh -i $(SSH_KEY_PATH) -o StrictHostKeyChecking=no" ./ ubuntu@123.45.67.89:/var/www/kijkeerst
    displayName: 'Deploy with rsync'

