trigger:
  - main

pool:
  name: 'Nawaf'  # Use your custom agent pool

jobs:
- job: InstallDependencies
  displayName: 'Install Dependencies'
  steps:
  - script: |
      curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      sudo apt-get install -y nodejs php7.4 php7.4-cli php7.4-fpm php7.4-mbstring php7.4-xml php7.4-zip
    displayName: 'Install Node.js, PHP 7.4'

- job: InstallComposer
  displayName: 'Install Composer Dependencies'
  dependsOn: InstallDependencies
  steps:
  - script: |
      curl -sS https://getcomposer.org/installer | php
      php composer.phar install --no-interaction --prefer-dist
    displayName: 'Install Composer Dependencies'

- job: RunMigrations
  displayName: 'Run Laravel Migrations'
  dependsOn: InstallComposer
  steps:
  - script: |
      php artisan migrate --force
    displayName: 'Run Laravel Migrations'

- job: CreateStorageLink
  displayName: 'Create Storage Link'
  dependsOn: RunMigrations
  steps:
  - script: |
      php artisan storage:link
    displayName: 'Create Storage Link'
