trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  sshEndpoint: 'kijkeerst-ssh'
  deployPath: '/var/www/kijkeerst'
  rsyncFilterFile: 'rsync-filter.txt'

jobs:
- job: LaravelDeploy
  displayName: 'Deploy Laravel to kijkeerst VPS'
  steps:

  - task: UseNode@1
    inputs:
      version: '18.x'
    displayName: 'Use Node.js 18'

  - script: |
      php -v
      composer --version || curl -sS https://getcomposer.org/installer | php && sudo mv composer.phar /usr/local/bin/composer
      composer install --no-interaction --prefer-dist --optimize-autoloader
    displayName: 'Install PHP Dependencies with Composer'

  - script: |
      npm ci
      npm run build
    displayName: 'Install and Build Frontend'

  - script: |
      php artisan migrate --force
      php artisan storage:link
    displayName: 'Run Laravel Artisan Commands'

  # Create rsync filter file for exclusion
  - script: |
      echo "- .git/" > $(rsyncFilterFile)
      echo "- node_modules/" >> $(rsyncFilterFile)
      echo "- storage/logs/" >> $(rsyncFilterFile)
      echo "- .env" >> $(rsyncFilterFile)
    displayName: 'Create rsync filter file'

  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: $(sshEndpoint)
      sourceFolder: '$(System.DefaultWorkingDirectory)'
      contents: '**/*'
      targetFolder: $(deployPath)
      cleanTargetFolder: false
      overwrite: true
    displayName: '[TEMP] Fallback File Sync - consider using rsync for delta updates'

  # Optionally: Use rsync via SSH for delta deployment (recommended)
  - script: |
      rsync -avz --delete --filter='merge $(rsyncFilterFile)' ./ $(sshEndpointUser)@$(sshEndpointHost):$(deployPath)
    condition: false # Set to `true` once SSH key auth + host known
    displayName: '[OPTIONAL] Rsync incremental deploy'

  # Set correct ownership (if needed)
  - task: SSH@0
    inputs:
      sshEndpoint: $(sshEndpoint)
      runOptions: 'inline'
      inline: |
        sudo chown -R www-data:www-data $(deployPath)
    displayName: 'Fix ownership to www-data'
