trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: build_and_deploy
  steps:
  - script: |
      curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      sudo apt-get install -y nodejs
    displayName: 'Install Node.js'

  - script: |
      sudo apt-get install -y php7.4 php7.4-cli php7.4-fpm php7.4-mbstring php7.4-xml php7.4-zip
    displayName: 'Install PHP 7.4'

  - script: |
      curl -sS https://getcomposer.org/installer | php
      php composer.phar install --no-interaction --prefer-dist
    displayName: 'Install Composer Dependencies'

  - script: |
      npm install
      npm run build
    displayName: 'Install and Build npm dependencies'

  - script: |
      php artisan migrate --force
    displayName: 'Run Laravel Migrations'

  - script: |
      php artisan storage:link
    displayName: 'Create Storage Link'
