trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  sshEndpoint: 'kijkeerst-ssh'
  deployPath: '/var/www/kijkeerst'
  rsyncFilterFile: 'rsync-filter.txt'

jobs:
- job: LaravelDeploy
  displayName: 'Deploy Laravel to kijkeerst VPS'
  steps:

  # Install frontend dependencies and build assets
  - script: |
      npm ci
      npm run build
    displayName: 'Install and Build Frontend'

  # Create rsync filter file for exclusion (vendor, node_modules, and .env)
  - script: |
      echo "- .git/" > $(rsyncFilterFile)
      echo "- node_modules/" >> $(rsyncFilterFile)
      echo "- storage/logs/" >> $(rsyncFilterFile)
      echo "- .env" >> $(rsyncFilterFile)
      echo "- vendor/" >> $(rsyncFilterFile)
    displayName: 'Create rsync filter file'

  # Copy files over SSH excluding vendor, node_modules, and .env
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: $(sshEndpoint)
      sourceFolder: '$(System.DefaultWorkingDirectory)'
      contents: '**/*'
      targetFolder: $(deployPath)
      cleanTargetFolder: false
      overwrite: true
    displayName: 'Copy Files to VPS'

  # Optionally: Use rsync via SSH for delta deployment (recommended)
  - script: |
      rsync -avz --delete --filter='merge $(rsyncFilterFile)' ./ $(sshEndpointUser)@$(sshEndpointHost):$(deployPath)
    condition: false # Set to `true` once SSH key auth + host known
    displayName: '[OPTIONAL] Rsync incremental deploy'

  # Set correct ownership (if needed)
  - task: SSH@0
    inputs:
      sshEndpoint: $(sshEndpoint)
      runOptions: 'inline'
      inline: |
        sudo chown -R www-data:www-data $(deployPath)
    displayName: 'Fix ownership to www-data'
