trigger:
  branches:
    include:
      - main

pool:
  name: 'Nawaf'

variables:
  SSH_USER: azureuser            # ← your SSH username on the VPS
  SSH_HOST: kijkeerst.nl         # ← your VPS domain or IP
  SSH_KEY: $(SSH_PRIVATE_KEY)    # ← pulled from variable group

stages:
- stage: Build
  jobs:
  - job: LaravelBuild
    displayName: 'Build Laravel App'
    steps:
    - task: UseNode@1
      inputs:
        version: '14.x'
    
    - script: |
        sudo apt-get update
        sudo apt-get install -y php php-mbstring php-xml php-zip unzip curl rsync openssh-client
      displayName: 'Install PHP & Tools'
    
    - script: |
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install --no-interaction --prefer-dist
      displayName: 'Install Composer'

    - script: |
        npm install
        npm run build
      displayName: 'Build Frontend'

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployToServer
    displayName: 'Deploy to VPS'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

          echo "Deploying to $SSH_HOST..."
          rsync -avz --exclude='.git' --exclude='node_modules' ./ $SSH_USER@$SSH_HOST:/var/www/html/kijkeerst.nl

          ssh $SSH_USER@$SSH_HOST "cd /var/www/html/kijkeerst.nl && php artisan migrate --force && php artisan storage:link"
